# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://olena-math.netlify.com'
baseurl: ''
title: 'Test'
description: 'This is my new website'
permalink: pretty
logo: "/assets/logos/logo@72px.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/
  Пошук: /search/

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://peopledotcom.files.wordpress.com/2019/08/math.jpg"

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  24: '/assets/logos/logo@24px.png'
  32: '/assets/logos/logo@32px.png'
  48: '/assets/logos/logo@48px.png'
  57: '/assets/logos/logo@57px.png'
  64: '/assets/logos/logo@64px.png'
  72: '/assets/logos/logo@72px.png'
  114: '/assets/logos/logo@114px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  152: '/assets/logos/logo@152px.png'
